#!/usr/bin/env bash

#Bash script that displays the content of the file /etc/passwd

#The script should only display:

#username
#user id
#home directory path for the user

FILENAME="/etc/passwd"

while IFS= read -r line
do
echo "$line"
done < $FILENAME