#!/usr/bin/env bash

#Bash script that displays the visitor IP along with the HTTP status code from the Apache log file:

#format:

#IP HTTP_CODE
#in a list

#download and commit the apache-access.log file along with your answers files

awk '{print $1,$9}' apache-access.log