#!/usr/bin/env bash

#Now that you have parsed the Apache log file, let’s sort the data

#Bash script that groups visitors by IP and HTTP status code, and displays this data:

#format:

#OCCURENCE_NUMBER IP HTTP_CODE
#in a list
#ordered from the greatest to the lowest number of occurrences

awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -nr