#!/usr/bin/env bash

#Bash script that gives you information about the school file:

#if the file exist or not
#if the file is empty or not
#if the file is a regular file or not

file=school

if [ -e $file ];
then
echo "$file file exists"

if [ -s $file ];
then
echo "$file file is not empty"
else [ -s $file ];
echo "$file file is empty"
fi

if [ -f $file ];
then
echo "$file is a regular file"
fi

else
echo "$file file does not exist"
fi