#!/usr/bin/env bash

#Bash script that displays numbers from 1 to 100:

#displays FizzBuzz when the number is a multiple of 3 and 5
#displays Fizz when the number is multiple of 3
#displays Buzz when the number is a multiple of 5
#otherwise, displays the number

#format: list

for i in {1..100}
do
if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]
then
echo "FizzBuzz"
elif [ $((i % 5)) -eq 0 ]
then
echo "Buzz"
elif [ $((i % 3)) -eq 0 ]
then
echo "Fizz"
else
echo $i
fi
done