#!/usr/bin/env bash

#Bash script manage_my_process that:

#indefinitely writes I am alive! to the file /tmp/my_process
#in between every I am alive! message, the program should pause for 2 seconds

while :
do
    echo "I am alive!" > /tmp/my_process
    sleep 2
done